// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH6TU5LvnIG-StIy-LZSYZtvz9uNsw8-w',
    appId: '1:461427160915:android:85d419f5499527ef82d3a6',
    messagingSenderId: '461427160915',
    projectId: 'pure-live-26c7f',
    storageBucket: 'pure-live-26c7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeP2bR4N5A9NqmeRlgQibbgHJm6gh5q1U',
    appId: '1:461427160915:ios:ecdf416614414ce482d3a6',
    messagingSenderId: '461427160915',
    projectId: 'pure-live-26c7f',
    storageBucket: 'pure-live-26c7f.firebasestorage.app',
    iosBundleId: 'com.mystyle.purelive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeP2bR4N5A9NqmeRlgQibbgHJm6gh5q1U',
    appId: '1:461427160915:ios:ecdf416614414ce482d3a6',
    messagingSenderId: '461427160915',
    projectId: 'pure-live-26c7f',
    storageBucket: 'pure-live-26c7f.firebasestorage.app',
    iosBundleId: 'com.mystyle.purelive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHqSY-juWseLzXRdq07e7xaKexEH7a1T0',
    appId: '1:461427160915:web:b1399df7920378d282d3a6',
    messagingSenderId: '461427160915',
    projectId: 'pure-live-26c7f',
    authDomain: 'pure-live-26c7f.firebaseapp.com',
    storageBucket: 'pure-live-26c7f.firebasestorage.app',
    measurementId: 'G-2LMYMW84SK',
  );
}
